name: aplikasi_penyewa
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  fluttertoast: ^8.2.2
  google_fonts: ^5.0.0
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
